using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine.InputSystem;

namespace Latios.Mash.Editor
{
    /// <summary>
    /// Writes a companion .Mash.g.cs file next to each .inputactions asset whenever the asset is
    /// imported. The companion holds the state components, event buffers, receiver, and the
    /// IMashGeneratedAsset that MashAuthoring's baker looks up by GUID.
    /// </summary>
    public class MashCodeGenPostprocessor : AssetPostprocessor
    {
        const string k_generatedMarker  = "// Generated by Mash for ";
        const string k_companionSuffix  = ".Mash.g.cs";

        static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            // Delete before generating. A moved asset keeps its GUID, so a companion left at the
            // old path would claim the same GUID as the new one.
            foreach (var path in deletedAssets)
            {
                if (IsMashSource(path))
                    DeleteCompanion(path);
            }
            foreach (var path in movedFromAssetPaths)
            {
                if (IsMashSource(path))
                    DeleteCompanion(path);
            }

            foreach (var path in movedAssets)
            {
                if (IsMashSource(path))
                    Generate(path);
            }
            foreach (var path in importedAssets)
            {
                if (IsMashSource(path))
                    Generate(path);
            }
        }

        static bool IsMashSource(string path) => IsInputActions(path) && IsWritableLocation(path);

        static bool IsInputActions(string path) => path.EndsWith(".inputactions", StringComparison.OrdinalIgnoreCase);

        // Only Assets/ and embedded or local packages are writable. Checking for an Assets/ prefix
        // isn't enough, since embedded packages live under Packages/. Anything else is in the
        // immutable package cache, where Unity rejects the companion with an error on every import.
        static bool IsWritableLocation(string assetPath)
        {
            var package = UnityEditor.PackageManager.PackageInfo.FindForAssetPath(assetPath);
            return package == null ||
                   package.source == UnityEditor.PackageManager.PackageSource.Embedded ||
                   package.source == UnityEditor.PackageManager.PackageSource.Local;
        }

        static string CompanionPath(string assetPath, string assetTypeName) =>
            Path.Combine(Path.GetDirectoryName(assetPath), assetTypeName + k_companionSuffix).Replace('\\', '/');

        // Only deletes files with Mash's generated header, so a hand-written file with a matching
        // name survives.
        static void DeleteCompanion(string assetPath)
        {
            if (!TryMakeIdentifiers(Path.GetFileNameWithoutExtension(assetPath), out var assetTypeName, out _))
                return;

            var companionPath = CompanionPath(assetPath, assetTypeName);
            if (!File.Exists(companionPath))
                return;

            string firstLines;
            try
            {
                firstLines = File.ReadAllText(companionPath);
            }
            catch (IOException)
            {
                return;
            }
            if (!firstLines.StartsWith("// <auto-generated>", StringComparison.Ordinal) || !firstLines.Contains(k_generatedMarker))
                return;

            AssetDatabase.DeleteAsset(companionPath);
        }

        enum FieldKind
        {
            Bool,
            Float,
            Int,
            Double,
            Float2,
            Float3,
            Quaternion,
        }

        class ActionInfo
        {
            public string          name;
            public string          typeName;   // UpperCamelCase
            public string          fieldName;  // camelCase
            public InputActionType type;
            public FieldKind       fieldKind;
            public int             eventChannelIndex;  // -1 for Value actions (no event channel)
        }

        class MapInfo
        {
            public string           name;
            public string           typeName;   // UpperCamelCase
            public string           fieldName;  // camelCase
            public List<ActionInfo> actions = new List<ActionInfo>();
            public int              eventChannelCount;
        }

        static void Generate(string assetPath)
        {
            var asset = AssetDatabase.LoadAssetAtPath<InputActionAsset>(assetPath);
            if (asset == null)
                return;

            var guid     = AssetDatabase.AssetPathToGUID(assetPath);
            var fileName = Path.GetFileNameWithoutExtension(assetPath);
            if (!TryMakeIdentifiers(fileName, out var assetTypeName, out _))
            {
                LogInvalidName(assetPath, $"asset file name \"{fileName}\"");
                return;
            }

            var maps        = new List<MapInfo>();
            var mapsByName  = new Dictionary<string, string>();
            var actionNames = new Dictionary<string, string>();
            foreach (var map in asset.actionMaps)
            {
                if (!TryMakeIdentifiers(map.name, out var mapTypeName, out var mapFieldName))
                {
                    LogInvalidName(assetPath, $"action map name \"{map.name}\"");
                    return;
                }
                if (!TryClaimName(mapsByName, mapFieldName, map.name, out var otherMap))
                {
                    LogNameClash(assetPath, $"action maps \"{otherMap}\" and \"{map.name}\"");
                    return;
                }

                var mapInfo      = new MapInfo { name = map.name, typeName = mapTypeName, fieldName = mapFieldName };
                int eventChannel = 0;
                actionNames.Clear();
                foreach (var action in map.actions)
                {
                    if (!TryMakeIdentifiers(action.name, out var actionTypeName, out var actionFieldName) || s_csharpKeywords.Contains(actionFieldName))
                    {
                        LogInvalidName(assetPath, $"action name \"{action.name}\" in map \"{map.name}\"");
                        return;
                    }
                    if (!TryClaimName(actionNames, actionFieldName, action.name, out var otherAction))
                    {
                        LogNameClash(assetPath, $"actions \"{otherAction}\" and \"{action.name}\" in map \"{map.name}\"");
                        return;
                    }

                    if (!TryGetFieldKind(action, out var fieldKind, out var diagnostic))
                    {
                        UnityEngine.Debug.LogError(
                            $"Mash: Skipping code generation for \"{assetPath}\" because action \"{action.name}\" in map \"{map.name}\" {diagnostic}.");
                        return;
                    }

                    var actionInfo = new ActionInfo
                    {
                        name      = action.name,
                        typeName  = actionTypeName,
                        fieldName = actionFieldName,
                        type      = action.type,
                        fieldKind = fieldKind,
                    };
                    if (action.type != InputActionType.Value)
                    {
                        actionInfo.eventChannelIndex = eventChannel;
                        eventChannel++;
                    }
                    else
                    {
                        actionInfo.eventChannelIndex = -1;
                    }
                    mapInfo.actions.Add(actionInfo);
                }
                mapInfo.eventChannelCount = eventChannel;
                maps.Add(mapInfo);
            }

            var code       = Emit(assetTypeName, fileName, guid, maps);
            var outputPath = CompanionPath(assetPath, assetTypeName);

            if (File.Exists(outputPath) && File.ReadAllText(outputPath) == code)
                return;

            File.WriteAllText(outputPath, code);
            AssetDatabase.ImportAsset(outputPath);
        }

        static void LogInvalidName(string assetPath, string subject)
        {
            UnityEngine.Debug.LogError(
                $"Mash: Skipping code generation for \"{assetPath}\" because the {subject} is not a valid C# name once everything but letters and digits is removed. " +
                "Rename it so it doesn't start with a digit, has at least one letter, and isn't a C# keyword.");
        }

        static void LogNameClash(string assetPath, string subjects)
        {
            UnityEngine.Debug.LogError(
                $"Mash: Skipping code generation for \"{assetPath}\" because the {subjects} generate the same C# name. " +
                "Rename one so they differ by more than punctuation, spaces, or capitalization.");
        }

        static bool TryClaimName(Dictionary<string, string> claimed, string generatedName, string originalName, out string existingOriginalName)
        {
            var key = generatedName.ToLowerInvariant();
            if (claimed.TryGetValue(key, out existingOriginalName))
                return false;
            claimed.Add(key, originalName);
            return true;
        }

        static readonly HashSet<string> s_csharpKeywords = new HashSet<string>
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue",
            "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally",
            "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params", "private", "protected",
            "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
            "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort",
            "using", "virtual", "void", "volatile", "while",
        };

        // Removes everything but letters and digits, then recases. Invalid names are rejected
        // rather than mangled, so users can predict the generated names.
        static bool TryMakeIdentifiers(string name, out string upperCamel, out string lowerCamel)
        {
            upperCamel = null;
            lowerCamel = null;

            var sb = new StringBuilder(name.Length);
            foreach (var c in name)
            {
                if (char.IsLetterOrDigit(c))
                    sb.Append(c);
            }
            if (sb.Length == 0 || char.IsDigit(sb[0]))
                return false;

            var stripped = sb.ToString();
            upperCamel   = char.ToUpperInvariant(stripped[0]) + stripped.Substring(1);
            lowerCamel   = ToLowerCamel(stripped);
            return true;
        }

        // "Move" -> "move", "UI" -> "ui", "UIElement" -> "uiElement"
        static string ToLowerCamel(string name)
        {
            int upperRun = 0;
            while (upperRun < name.Length && char.IsUpper(name[upperRun]))
                upperRun++;
            if (upperRun == 0)
                return name;
            // A capital that starts the next word stays capitalized.
            if (upperRun < name.Length)
                upperRun--;
            if (upperRun == 0)
                upperRun = 1;
            return name.Substring(0, upperRun).ToLowerInvariant() + name.Substring(upperRun);
        }

        // Uses the layout registry instead of a table of layout names, so custom layouts work.
        static bool TryGetFieldKind(InputAction action, out FieldKind kind, out string diagnostic)
        {
            kind       = default;
            diagnostic = null;

            // A Button action is exposed as a bool no matter which layout backs it.
            if (action.type == InputActionType.Button)
                return true;

            var controlType = action.expectedControlType;
            if (string.IsNullOrEmpty(controlType))
            {
                diagnostic = "has its Control Type set to \"Any\". Mash needs a concrete Control Type to pick the field type";
                return false;
            }
            if (controlType == "Button")
                return true;

            var valueType = ResolveLayoutValueType(controlType);
            if (valueType == null)
            {
                diagnostic = $"has Control Type \"{controlType}\", which is not a registered input control layout";
                return false;
            }

            if (valueType == typeof(float))
                kind = FieldKind.Float;
            else if (valueType == typeof(int))
                kind = FieldKind.Int;
            else if (valueType == typeof(double))
                kind = FieldKind.Double;
            else if (valueType == typeof(UnityEngine.Vector2))
                kind = FieldKind.Float2;
            else if (valueType == typeof(UnityEngine.Vector3))
                kind = FieldKind.Float3;
            else if (valueType == typeof(UnityEngine.Quaternion))
                kind = FieldKind.Quaternion;
            else
            {
                diagnostic =
                    $"has Control Type \"{controlType}\", whose values are {valueType.Name}. Mash supports control types whose values are float, int, double, Vector2, Vector3, or Quaternion";
                return false;
            }
            return true;
        }

        // Walks the layout's control type up to InputControl<T> and returns T.
        static Type ResolveLayoutValueType(string layoutName)
        {
            UnityEngine.InputSystem.Layouts.InputControlLayout layout;
            try
            {
                layout = InputSystem.LoadLayout(layoutName);
            }
            catch (Exception)
            {
                return null;
            }
            if (layout == null)
                return null;

            for (var type = layout.type; type != null; type = type.BaseType)
            {
                if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(InputControl<>))
                    return type.GetGenericArguments()[0];
            }
            return null;
        }

        static string FieldTypeName(FieldKind kind)
        {
            switch (kind)
            {
                case FieldKind.Bool: return "bool";
                case FieldKind.Int: return "int";
                case FieldKind.Double: return "double";
                case FieldKind.Float2: return "float2";
                case FieldKind.Float3: return "float3";
                case FieldKind.Quaternion: return "quaternion";
                default: return "float";
            }
        }

        // The underscore keeps map "A" + action "BC" apart from map "AB" + action "C".
        static string ActionField(MapInfo map, ActionInfo action) => $"m_{map.fieldName}_{action.fieldName}";

        static string CallbackName(MapInfo map, ActionInfo action) => $"On{map.typeName}_{action.typeName}";

        static string PendingEventsField(MapInfo map) => $"m_{map.fieldName}PendingEvents";

        static string PollExpression(MapInfo map, ActionInfo action)
        {
            var field = ActionField(map, action);
            switch (action.fieldKind)
            {
                case FieldKind.Bool: return $"{field}.IsPressed()";
                case FieldKind.Int: return $"{field}.ReadValue<int>()";
                case FieldKind.Double: return $"{field}.ReadValue<double>()";
                case FieldKind.Float2: return $"{field}.ReadValue<UnityEngine.Vector2>()";
                case FieldKind.Float3: return $"{field}.ReadValue<UnityEngine.Vector3>()";
                case FieldKind.Quaternion: return $"{field}.ReadValue<UnityEngine.Quaternion>()";
                default: return $"{field}.ReadValue<float>()";
            }
        }

        static string Emit(string assetTypeName, string sourceFileName, string guid, List<MapInfo> maps)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"{k_generatedMarker}\"{sourceFileName}.inputactions\". Don't edit this file. Mash rewrites it whenever the asset is imported.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Latios;");
            sb.AppendLine("using Latios.Mash;");
            sb.AppendLine("using Latios.Mash.Authoring;");
            sb.AppendLine("using Unity.Entities;");
            sb.AppendLine("using Unity.Mathematics;");
            sb.AppendLine("using UnityEngine.InputSystem;");
            sb.AppendLine();
            sb.AppendLine("namespace Latios.Mash.Generated");
            sb.AppendLine("{");

            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// The asset this entity was baked from, and the entity's private copy of it. Use runtimeAsset for");
            sb.AppendLine("    /// rebinding. Mash sets runtimeAsset when it sets up the entity.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public struct {assetTypeName}_AssetRef : IComponentData, IMashAssetRef");
            sb.AppendLine("    {");
            sb.AppendLine("        public UnityObjectRef<InputActionAsset> sourceAsset;");
            sb.AppendLine("        public UnityObjectRef<InputActionAsset> runtimeAsset;");
            sb.AppendLine();
            sb.AppendLine("        UnityObjectRef<InputActionAsset> IMashAssetRef.sourceAsset => sourceAsset;");
            sb.AppendLine("        UnityObjectRef<InputActionAsset> IMashAssetRef.runtimeAsset { get => runtimeAsset; set => runtimeAsset = value; }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Added when Mash can't set up this asset on the entity. Mash ignores the asset on this entity");
            sb.AppendLine("    /// until you remove this component.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public struct {assetTypeName}_InitializationFailed : IComponentData {{ }}");
            sb.AppendLine();

            foreach (var map in maps)
            {
                sb.AppendLine($"    public struct {assetTypeName}_{map.typeName}State : IComponentData");
                sb.AppendLine("    {");
                foreach (var action in map.actions)
                    sb.AppendLine($"        public {FieldTypeName(action.fieldKind)} {action.fieldName};");
                sb.AppendLine("    }");
                sb.AppendLine();

                if (map.eventChannelCount > 0)
                {
                    sb.AppendLine(
                        $"    public struct {assetTypeName}_{map.typeName}EventHeader : IBufferElementData {{ public MultiListHeader<MashActionEvent> value; }}");
                    sb.AppendLine(
                        $"    public struct {assetTypeName}_{map.typeName}EventElement : IBufferElementData {{ public MultiListElement<MashActionEvent> value; }}");
                    sb.AppendLine();

                    sb.AppendLine($"    public static class {assetTypeName}_{map.typeName}EventChannels");
                    sb.AppendLine("    {");
                    foreach (var action in map.actions.Where(a => a.eventChannelIndex >= 0))
                        sb.AppendLine($"        public const int {action.fieldName} = {action.eventChannelIndex};");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
            }

            // The callbacks must live on a class. Managed struct components are copied on every
            // get, so a callback bound to one copy can't be unsubscribed from another.
            sb.AppendLine($"    public sealed class {assetTypeName}_ReceiverImpl");
            sb.AppendLine("    {");
            sb.AppendLine("        InputActionAsset m_runtimeAsset;");
            foreach (var map in maps)
            {
                foreach (var action in map.actions)
                    sb.AppendLine($"        InputAction {ActionField(map, action)};");
                if (map.eventChannelCount > 0)
                    sb.AppendLine($"        List<MashActionEvent> {PendingEventsField(map)};");
            }
            sb.AppendLine();

            sb.AppendLine("        public bool isInitialized => m_runtimeAsset != null;");
            sb.AppendLine();
            sb.AppendLine("        public InputActionAsset runtimeAsset => m_runtimeAsset;");
            sb.AppendLine();

            sb.AppendLine("        public void Initialize(InputActionAsset runtimeAsset)");
            sb.AppendLine("        {");
            sb.AppendLine("            m_runtimeAsset = runtimeAsset;");
            foreach (var map in maps)
            {
                var mapLocal = $"{map.fieldName}Map";
                sb.AppendLine($"            var {mapLocal} = runtimeAsset.FindActionMap(\"{map.name}\", true);");
                foreach (var action in map.actions)
                    sb.AppendLine($"            {ActionField(map, action)} = {mapLocal}.FindAction(\"{action.name}\");");
                if (map.eventChannelCount > 0)
                {
                    sb.AppendLine($"            {PendingEventsField(map)} = new List<MashActionEvent>();");
                    foreach (var action in map.actions.Where(a => a.eventChannelIndex >= 0))
                    {
                        sb.AppendLine($"            {ActionField(map, action)}.started += {CallbackName(map, action)};");
                        sb.AppendLine($"            {ActionField(map, action)}.performed += {CallbackName(map, action)};");
                        sb.AppendLine($"            {ActionField(map, action)}.canceled += {CallbackName(map, action)};");
                    }
                }
                sb.AppendLine($"            {mapLocal}.Enable();");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var map in maps)
            {
                foreach (var action in map.actions.Where(a => a.eventChannelIndex >= 0))
                {
                    sb.AppendLine($"        void {CallbackName(map, action)}(InputAction.CallbackContext ctx)");
                    sb.AppendLine("        {");
                    sb.AppendLine(
                        $"            {PendingEventsField(map)}.Add(new MashActionEvent {{ actionIndex = {assetTypeName}_{map.typeName}EventChannels.{action.fieldName}, phase = ctx.phase, time = ctx.time, duration = ctx.duration, value = ReadValueAsFloat4(ctx) }});");
                    sb.AppendLine("        }");
                }
            }
            sb.AppendLine();

            sb.AppendLine("        public void PollAndDrain(EntityManager entityManager, Entity entity)");
            sb.AppendLine("        {");
            foreach (var map in maps)
            {
                sb.AppendLine("            {");
                sb.AppendLine($"                var state = entityManager.GetComponentData<{assetTypeName}_{map.typeName}State>(entity);");
                foreach (var action in map.actions)
                    sb.AppendLine($"                state.{action.fieldName} = {PollExpression(map, action)};");
                sb.AppendLine("                entityManager.SetComponentData(entity, state);");
                if (map.eventChannelCount > 0)
                {
                    sb.AppendLine(
                        $"                var headerBuffer = entityManager.GetBuffer<{assetTypeName}_{map.typeName}EventHeader>(entity).Reinterpret<MultiListHeader<MashActionEvent>>();");
                    sb.AppendLine(
                        $"                var elementBuffer = entityManager.GetBuffer<{assetTypeName}_{map.typeName}EventElement>(entity).Reinterpret<MultiListElement<MashActionEvent>>();");
                    sb.AppendLine("                var multiList = new DynamicMultiList<MashActionEvent>(headerBuffer, elementBuffer);");
                    sb.AppendLine($"                for (int channel = 0; channel < {map.eventChannelCount}; channel++)");
                    sb.AppendLine("                    multiList[channel].Clear();");
                    sb.AppendLine($"                foreach (var evt in {PendingEventsField(map)})");
                    sb.AppendLine("                    multiList[evt.actionIndex].Add(evt);");
                    sb.AppendLine($"                {PendingEventsField(map)}.Clear();");
                }
                sb.AppendLine("            }");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public void Uninitialize()");
            sb.AppendLine("        {");
            foreach (var map in maps)
            {
                foreach (var action in map.actions.Where(a => a.eventChannelIndex >= 0))
                {
                    sb.AppendLine($"            if ({ActionField(map, action)} != null)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {ActionField(map, action)}.started -= {CallbackName(map, action)};");
                    sb.AppendLine($"                {ActionField(map, action)}.performed -= {CallbackName(map, action)};");
                    sb.AppendLine($"                {ActionField(map, action)}.canceled -= {CallbackName(map, action)};");
                    sb.AppendLine("            }");
                }
            }
            foreach (var map in maps)
            {
                foreach (var action in map.actions)
                    sb.AppendLine($"            {ActionField(map, action)} = null;");
                if (map.eventChannelCount > 0)
                    sb.AppendLine($"            {PendingEventsField(map)} = null;");
            }
            sb.AppendLine("            MashRuntimeAsset.Destroy(m_runtimeAsset);");
            sb.AppendLine("            m_runtimeAsset = null;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void Dispose() => Uninitialize();");
            sb.AppendLine();

            sb.AppendLine("        static float4 ReadValueAsFloat4(InputAction.CallbackContext ctx)");
            sb.AppendLine("        {");
            sb.AppendLine("            var t = ctx.valueType;");
            sb.AppendLine("            if (t == typeof(float)) return new float4(ctx.ReadValue<float>(), 0f, 0f, 0f);");
            sb.AppendLine("            if (t == typeof(int)) return new float4(ctx.ReadValue<int>(), 0f, 0f, 0f);");
            sb.AppendLine("            if (t == typeof(double)) return new float4((float)ctx.ReadValue<double>(), 0f, 0f, 0f);");
            sb.AppendLine(
                "            if (t == typeof(UnityEngine.Vector2)) { var v = ctx.ReadValue<UnityEngine.Vector2>(); return new float4(v.x, v.y, 0f, 0f); }");
            sb.AppendLine(
                "            if (t == typeof(UnityEngine.Vector3)) { var v = ctx.ReadValue<UnityEngine.Vector3>(); return new float4(v.x, v.y, v.z, 0f); }");
            sb.AppendLine(
                "            if (t == typeof(UnityEngine.Quaternion)) { var v = ctx.ReadValue<UnityEngine.Quaternion>(); return new float4(v.x, v.y, v.z, v.w); }");
            sb.AppendLine("            if (t == typeof(bool)) return new float4(ctx.ReadValueAsButton() ? 1f : 0f, 0f, 0f, 0f);");
            sb.AppendLine("            return default;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    public partial struct {assetTypeName}_Receiver : IManagedStructComponent, System.IDisposable, IMashReceiver");
            sb.AppendLine("    {");
            sb.AppendLine($"        {assetTypeName}_ReceiverImpl impl;");
            sb.AppendLine();
            sb.AppendLine("        public bool isInitialized => impl != null && impl.isInitialized;");
            sb.AppendLine();
            sb.AppendLine("        public InputActionAsset runtimeAsset => impl?.runtimeAsset;");
            sb.AppendLine();
            sb.AppendLine("        public void Initialize(InputActionAsset runtimeAsset)");
            sb.AppendLine("        {");
            sb.AppendLine($"            impl = new {assetTypeName}_ReceiverImpl();");
            sb.AppendLine("            impl.Initialize(runtimeAsset);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void PollAndDrain(EntityManager entityManager, Entity entity) => impl.PollAndDrain(entityManager, entity);");
            sb.AppendLine();
            sb.AppendLine("        public void Uninitialize() => impl?.Uninitialize();");
            sb.AppendLine();
            sb.AppendLine("        public void Dispose() => Uninitialize();");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    public class {assetTypeName}_GeneratedAsset : IMashGeneratedAsset");
            sb.AppendLine("    {");
            sb.AppendLine($"        public string sourceAssetGuid => \"{guid}\";");
            sb.AppendLine($"        public System.Type receiverType => typeof({assetTypeName}_Receiver);");
            sb.AppendLine($"        public System.Type assetRefType => typeof({assetTypeName}_AssetRef);");
            sb.AppendLine($"        public System.Type initializationFailedType => typeof({assetTypeName}_InitializationFailed);");
            sb.AppendLine();
            sb.AppendLine("        public void Bake(Baker<MashAuthoring> baker, Entity entity, InputActionAsset sourceAsset)");
            sb.AppendLine("        {");
            sb.AppendLine($"            baker.AddComponent(entity, new {assetTypeName}_AssetRef {{ sourceAsset = sourceAsset }});");
            foreach (var map in maps)
            {
                sb.AppendLine($"            baker.AddComponent(entity, new {assetTypeName}_{map.typeName}State());");
                if (map.eventChannelCount > 0)
                {
                    sb.AppendLine("            {");
                    sb.AppendLine(
                        $"                var headerBuffer = baker.AddBuffer<{assetTypeName}_{map.typeName}EventHeader>(entity).Reinterpret<MultiListHeader<MashActionEvent>>();");
                    sb.AppendLine(
                        $"                var elementBuffer = baker.AddBuffer<{assetTypeName}_{map.typeName}EventElement>(entity).Reinterpret<MultiListElement<MashActionEvent>>();");
                    sb.AppendLine("                var multiList = new DynamicMultiList<MashActionEvent>(headerBuffer, elementBuffer);");
                    foreach (var action in map.actions.Where(a => a.eventChannelIndex >= 0))
                    {
                        sb.AppendLine($"                var {action.fieldName}Channel = multiList.CreateList();");
                        sb.AppendLine(
                            $"                UnityEngine.Debug.Assert({action.fieldName}Channel == {assetTypeName}_{map.typeName}EventChannels.{action.fieldName}, \"Mash: Channel index mismatch for action \\\"{action.name}\\\" in map \\\"{map.name}\\\". This is a bug in Mash, please report it.\");");
                    }
                    sb.AppendLine("            }");
                }
            }
            sb.AppendLine($"            baker.AddComponent<{assetTypeName}_Receiver.ExistComponent>(entity);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
